* dotfiles
A repository of configuration files optimized for FactSet Engineering environments
**  Quick Start
*** Clone this repository
Start by cloning this repository into your home directory by running the following command:
=$ git clone git@gitlab.factset.com:amavrakis/dotfiles.git ~/=
*** Upgrade your software
**** Quick Upgrade (not recommended)
In the process of setting up my environment I've installed a few dependencies into my =~/local/bin/= dir add the following line to your =~/.profile-user= to bootstrap the setup process:

~export PATH=home/user/amavrakis/local/bin/:$PATH~
**** Custom Upgrade
It is recommended that you check out all of the software in that directory and source them one by one or install them from source.

e.g. ~export PATH=home/user/amavrakis/local/bin/emacs:$PATH~

If you wish to install software from source, most likely you will need to prefix the configuration with a flag...something like this:

=$ ./configure --prefix=/home/user/<your-username>/local/=

*** GNU Stow
GNU stow is a simple utility to make configuration file management easier. If you want to use a configuration in this directory and you have stow installed or you've sourced my =~/local/bin/= directory, follow the steps below to quickly soft link these files into your home dir.

To link configurations for individual applications, start with backing up the files for that application (the example below is for emacs):

=$ mv ~/.emacs ~/.emacs.bkp/ && mv ~/.emacs.d/ ~/.emacs.d.bkp/=

To execute the link:

=$ cd ~/dotfiles=
=$ stow emacs=
*** That's All Folks!
Yup. That's it. You could always copy the files manually, but ask yourself, "Self, why?" Fork this repository to keep all of your configuration files in one place, clone them anywhere, and boost your productivity.
